#!/usr/bin/env python3
"""Generates supabase/v2-fresh/{schema,functions,triggers,rls,storage}.sql from the numbered
migrations (single source of truth) + the fresh-only base files. Run: python3 scripts/build-fresh.py
Tag blocks inside a migration with -- @@SCHEMA | -- @@FUNCTIONS | -- @@TRIGGERS | -- @@POLICIES."""
import glob, os, re
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
mig = sorted(glob.glob(os.path.join(root, 'supabase/migrations/*.sql')))
fresh = os.path.join(root, 'supabase/v2-fresh')
parts = {'SCHEMA': [], 'FUNCTIONS': [], 'TRIGGERS': [], 'POLICIES': []}
for f in mig:
    name = os.path.basename(f)
    if 'OPTIONAL' in name:      # 900 is superseded by 008 and must never be combined with it
        continue
    text = open(f).read()
    for m in re.finditer(r'^-- @@(SCHEMA|FUNCTIONS|TRIGGERS|POLICIES)\n(.*?)(?=^-- @@|\Z)', text, re.S | re.M):
        parts[m.group(1)].append(f'-- ---- from migrations/{name} ----\n{m.group(2).strip()}\n')
BANNER = ('-- #####################################################################\n'
          '-- FRESH V2 DATABASE ONLY - DO NOT RUN ON AN EXISTING CAMPUSDESK V1 DATABASE\n'
          '-- GENERATED by scripts/build-fresh.py - edit supabase/migrations/* instead.\n'
          '-- #####################################################################\n\n')
def w(name, body): open(os.path.join(fresh, name), 'w').write(BANNER + body)
w('schema.sql', open(os.path.join(fresh, '_base_tables.sql')).read() + '\n' + '\n'.join(parts['SCHEMA']))
w('functions.sql', '\n'.join(parts['FUNCTIONS']))
w('triggers.sql', '\n'.join(parts['TRIGGERS']))
w('rls.sql', open(os.path.join(fresh, '_rls_base.sql')).read() + '\n' + '\n'.join(parts['POLICIES']))
w('storage.sql', open(os.path.join(fresh, '_storage_base.sql')).read())
print('built', [n for n in ('schema','functions','triggers','rls','storage')])
