-- #####################################################################
-- FRESH V2 DATABASE ONLY - DO NOT RUN ON AN EXISTING CAMPUSDESK V1 DATABASE
-- GENERATED by scripts/build-fresh.py - edit supabase/migrations/* instead.
-- #####################################################################

-- ---- from migrations/001_v2_base_compatibility.sql ----
-- Same names/semantics as V1 (create or replace is safe).
create or replace function public.get_my_role()
returns text language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create or replace function public.in_class(cid uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select cid is not null and (
       exists (select 1 from public.students s where s.class_id = cid and (s.id = auth.uid() or s.parent_id = auth.uid()))
    or exists (select 1 from public.teacher_subjects ts where ts.class_id = cid and ts.teacher_id = auth.uid())
    or exists (select 1 from public.classes c where c.id = cid and c.class_teacher_id = auth.uid())
  );
$$;

create or replace function public.teaches_student(sid uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.students s
    where s.id = sid and (
      exists (select 1 from public.teacher_subjects ts where ts.class_id = s.class_id and ts.teacher_id = auth.uid())
      or exists (select 1 from public.classes c where c.id = s.class_id and c.class_teacher_id = auth.uid())
    )
  );
$$;

create or replace function public.is_parent_of(sid uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.students s where s.id = sid and s.parent_id = auth.uid());
$$;

create or replace function public.can_view_profile(target uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select
       auth.uid() = target
    or public.is_admin()
    or exists (select 1 from public.profiles p where p.id = target and p.role in ('teacher','admin'))
    or exists (select 1 from public.students s where s.id = auth.uid() and s.parent_id = target)
    or exists (select 1 from public.students s where s.id = target and s.parent_id = auth.uid())
    or exists (select 1 from public.students s
               where (s.id = target or s.parent_id = target) and public.teaches_student(s.id));
$$;

-- ---- from migrations/002_v2_fee_integrity.sql ----
create or replace function public.next_receipt_no()
returns text language sql volatile as $$
  select 'RCPT-' || to_char(now(), 'YYYY') || '-' || to_char(nextval('public.fee_receipt_seq'), 'FM000000');
$$;

-- Single source of truth for per-fee numbers. Only CONFIRMED payments reduce the balance.
create or replace function public.get_fee_summary(p_student uuid)
returns table (
  fee_structure_id uuid, fee_type text, amount numeric, due_date date,
  confirmed_paid numeric, pending_amount numeric, remaining numeric, status text, can_pay boolean,
  pending_payment_id uuid, pending_date date, pending_mode text, pending_reference text,
  last_rejection_reason text, last_rejected_at timestamptz
)
language plpgsql stable security definer set search_path = public as $$
begin
  if not (auth.uid() = p_student or public.is_admin() or public.is_parent_of(p_student)) then
    raise exception 'campusdesk:not_allowed' using errcode = '42501';
  end if;
  return query
  select fs.id, fs.fee_type, fs.amount, fs.due_date,
         c.confirmed, coalesce(pd.amount_paid, 0), greatest(fs.amount - c.confirmed, 0),
         case
           when fs.amount - c.confirmed <= 0 then 'paid'
           when pd.id is not null then 'pending_verification'
           when c.confirmed > 0 then 'partial'
           when rj.id is not null then 'rejected'
           else 'due'
         end,
         (fs.amount - c.confirmed > 0 and pd.id is null),
         pd.id, pd.payment_date, pd.mode, pd.reference_note,
         rj.rejection_reason, rj.verified_at
  from public.students s
  join public.fee_structure fs on fs.class_id = s.class_id
  cross join lateral (
    select coalesce(sum(p.amount_paid), 0) as confirmed
    from public.fee_payments p
    where p.student_id = s.id and p.fee_structure_id = fs.id and p.status in ('paid','partial')
  ) c
  left join lateral (
    select p.* from public.fee_payments p
    where p.student_id = s.id and p.fee_structure_id = fs.id and p.status = 'pending_verification'
    order by p.created_at desc limit 1
  ) pd on true
  left join lateral (
    select p.* from public.fee_payments p
    where p.student_id = s.id and p.fee_structure_id = fs.id and p.status = 'rejected'
    order by coalesce(p.verified_at, p.created_at) desc limit 1
  ) rj on true
  where s.id = p_student
  order by fs.due_date nulls last, fs.fee_type;
end $$;

-- Student or parent submits a payment claim -> pending_verification
create or replace function public.submit_fee_payment(
  p_student uuid, p_fee uuid, p_amount numeric, p_mode text, p_reference text default null)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_id uuid;
begin
  if not (auth.uid() = p_student or public.is_parent_of(p_student)) then
    raise exception 'campusdesk:not_allowed' using errcode = '42501';
  end if;
  if not exists (select 1 from public.students s join public.fee_structure f on f.class_id = s.class_id
                 where s.id = p_student and f.id = p_fee) then
    raise exception 'campusdesk:fee_not_applicable' using errcode = 'P0001';
  end if;
  if coalesce(trim(p_mode), '') = '' then
    raise exception 'campusdesk:mode_required' using errcode = 'P0001';
  end if;
  insert into public.fee_payments (student_id, fee_structure_id, amount_paid, payment_date, mode,
                                   status, reference_note, submitted_by)
  values (p_student, p_fee, round(p_amount, 2), current_date, trim(p_mode),
          'pending_verification', nullif(trim(coalesce(p_reference, '')), ''), auth.uid())
  returning id into v_id;   -- fee_payments_guard() enforces amount/overpay/duplicate rules
  return v_id;
end $$;

create or replace function public.verify_fee_payment(p_payment uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
declare r public.fee_payments;
begin
  if not public.is_admin() then raise exception 'campusdesk:not_allowed' using errcode = '42501'; end if;
  select * into r from public.fee_payments where id = p_payment for update;
  if not found then raise exception 'campusdesk:not_found' using errcode = 'P0001'; end if;
  if r.status <> 'pending_verification' then raise exception 'campusdesk:not_pending' using errcode = 'P0001'; end if;
  update public.fee_payments
     set status = 'paid',                      -- guard trigger normalises to paid/partial
         verified_by = auth.uid(), verified_at = now(), receipt_no = public.next_receipt_no()
   where id = p_payment returning * into r;
  insert into public.audit_logs (actor_id, action, target_table, target_id, details)
  values (auth.uid(), 'verify_fee_payment', 'fee_payments', r.id,
          jsonb_build_object('amount', r.amount_paid, 'receipt', r.receipt_no, 'status', r.status));
  return jsonb_build_object('id', r.id, 'status', r.status, 'receipt_no', r.receipt_no);
end $$;

create or replace function public.reject_fee_payment(p_payment uuid, p_reason text default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare r public.fee_payments;
begin
  if not public.is_admin() then raise exception 'campusdesk:not_allowed' using errcode = '42501'; end if;
  select * into r from public.fee_payments where id = p_payment for update;
  if not found then raise exception 'campusdesk:not_found' using errcode = 'P0001'; end if;
  if r.status <> 'pending_verification' then raise exception 'campusdesk:not_pending' using errcode = 'P0001'; end if;
  update public.fee_payments
     set status = 'rejected', rejection_reason = nullif(trim(coalesce(p_reason, '')), ''),
         verified_by = auth.uid(), verified_at = now()
   where id = p_payment returning * into r;
  insert into public.audit_logs (actor_id, action, target_table, target_id, details)
  values (auth.uid(), 'reject_fee_payment', 'fee_payments', r.id,
          jsonb_build_object('amount', r.amount_paid, 'reason', r.rejection_reason));
  return jsonb_build_object('id', r.id, 'status', r.status);
end $$;

-- Admin records an offline (cash/cheque) payment that is already confirmed.
create or replace function public.admin_record_payment(
  p_student uuid, p_fee uuid, p_amount numeric, p_mode text, p_reference text default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare r public.fee_payments;
begin
  if not public.is_admin() then raise exception 'campusdesk:not_allowed' using errcode = '42501'; end if;
  insert into public.fee_payments (student_id, fee_structure_id, amount_paid, payment_date, mode, status,
                                   reference_note, submitted_by, verified_by, verified_at, receipt_no, recorded_by)
  values (p_student, p_fee, round(p_amount, 2), current_date, coalesce(nullif(trim(p_mode), ''), 'cash'), 'paid',
          nullif(trim(coalesce(p_reference, '')), ''), auth.uid(), auth.uid(), now(), public.next_receipt_no(), auth.uid())
  returning * into r;
  insert into public.audit_logs (actor_id, action, target_table, target_id, details)
  values (auth.uid(), 'record_fee_payment', 'fee_payments', r.id,
          jsonb_build_object('amount', r.amount_paid, 'receipt', r.receipt_no));
  return jsonb_build_object('id', r.id, 'status', r.status, 'receipt_no', r.receipt_no);
end $$;

-- Official receipt data. Only for confirmed payments.
create or replace function public.get_payment_receipt(p_payment uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare r public.fee_payments; v jsonb;
begin
  select * into r from public.fee_payments where id = p_payment;
  if not found then raise exception 'campusdesk:not_found' using errcode = 'P0001'; end if;
  if not (auth.uid() = r.student_id or public.is_admin() or public.is_parent_of(r.student_id)) then
    raise exception 'campusdesk:not_allowed' using errcode = '42501';
  end if;
  if r.status not in ('paid','partial') or r.receipt_no is null then
    raise exception 'campusdesk:no_receipt' using errcode = 'P0001';
  end if;
  select jsonb_build_object(
    'receipt_no', r.receipt_no, 'amount', r.amount_paid, 'payment_date', r.payment_date, 'mode', r.mode,
    'reference', r.reference_note, 'verified_at', r.verified_at,
    'verified_by', (select full_name from public.profiles where id = r.verified_by),
    'student_name', sp.full_name, 'roll_no', s.roll_no,
    'class', c.name || '-' || c.section, 'academic_year', c.academic_year,
    'fee_type', f.fee_type, 'fee_amount', f.amount)
  into v
  from public.students s
  join public.profiles sp on sp.id = s.id
  left join public.classes c on c.id = s.class_id
  left join public.fee_structure f on f.id = r.fee_structure_id
  where s.id = r.student_id;
  return v;
end $$;

-- ---- from migrations/003_v2_report_support.sql ----
create or replace function public.attendance_percent(p_attended bigint, p_counted bigint)
returns integer language sql immutable as $$
  select case when coalesce(p_counted, 0) = 0 then null else round(100.0 * p_attended / p_counted)::int end;
$$;

create or replace function public.grade_for(p numeric)
returns text language sql immutable as $$
  select case when p is null then null when p >= 90 then 'A+' when p >= 80 then 'A' when p >= 70 then 'B'
              when p >= 60 then 'C' when p >= 50 then 'D' else 'F' end;
$$;

create or replace function public.assign_student_code()
returns trigger language plpgsql as $$
begin
  if new.student_code is null then
    new.student_code := 'STU-' || to_char(coalesce(new.admission_date, current_date), 'YYYY') || '-' ||
                        to_char(nextval('public.student_code_seq'), 'FM000');
  end if;
  return new;
end $$;

create or replace function public.assign_teacher_code()
returns trigger language plpgsql as $$
begin
  if new.teacher_code is null then
    new.teacher_code := 'TCH-' || to_char(coalesce(new.joining_date, current_date), 'YYYY') || '-' ||
                        to_char(nextval('public.teacher_code_seq'), 'FM000');
  end if;
  return new;
end $$;

-- Report payload. Students/parents only ever see PUBLISHED results; staff see marks as entered.
create or replace function public.get_student_report(p_student uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v_staff boolean; v jsonb;
begin
  if not (auth.uid() = p_student or public.is_admin() or public.is_parent_of(p_student) or public.teaches_student(p_student)) then
    raise exception 'campusdesk:not_allowed' using errcode = '42501';
  end if;
  v_staff := public.is_admin() or public.teaches_student(p_student);

  select jsonb_build_object(
    'generated_at', now(),
    'student', jsonb_build_object(
        'id', s.id, 'student_code', s.student_code, 'roll_no', s.roll_no, 'name', sp.full_name,
        'email', sp.email, 'phone', sp.phone, 'dob', s.dob, 'gender', s.gender,
        'class_name', c.name, 'section', c.section, 'academic_year', c.academic_year),
    'class_teacher', case when ct.id is null then null else jsonb_build_object(
        'name', ctp.full_name, 'email', ctp.email, 'phone', ctp.phone, 'teacher_code', ct.teacher_code) end,
    'guardian', case when pp.id is null then null else jsonb_build_object(
        'name', pp.full_name, 'email', pp.email, 'phone', pp.phone) end,
    'attendance', coalesce((
        select jsonb_agg(jsonb_build_object('subject', x.subject, 'present', x.present, 'late', x.late,
                                            'absent', x.absent, 'leave', x.leave_n) order by x.subject)
        from (select coalesce(sb.name, 'Unassigned') as subject,
                     count(*) filter (where a.status = 'present') as present,
                     count(*) filter (where a.status = 'late') as late,
                     count(*) filter (where a.status = 'absent') as absent,
                     count(*) filter (where a.status = 'leave') as leave_n
              from public.attendance a left join public.subjects sb on sb.id = a.subject_id
              where a.student_id = s.id group by sb.name) x), '[]'::jsonb),
    'marks', coalesce((
        select jsonb_agg(jsonb_build_object(
                 'exam', e.name, 'term', e.term, 'exam_date', e.start_date, 'subject', sb.name,
                 'obtained', m.marks_obtained, 'max', m.max_marks,
                 'percentage', round(100.0 * m.marks_obtained / nullif(m.max_marks, 0), 1),
                 'grade', public.grade_for(100.0 * m.marks_obtained / nullif(m.max_marks, 0)))
               order by e.start_date nulls last, e.name, sb.name)
        from public.marks m
        join public.exams e on e.id = m.exam_id
        join public.subjects sb on sb.id = m.subject_id
        where m.student_id = s.id
          and (v_staff or exists (select 1 from public.results r where r.student_id = m.student_id and r.exam_id = m.exam_id and r.published))
    ), '[]'::jsonb),
    'results', coalesce((
        select jsonb_agg(jsonb_build_object('exam', e.name, 'term', e.term, 'exam_date', e.start_date,
                 'total', r.total_marks, 'percentage', r.percentage, 'grade', r.grade, 'rank', r.rank, 'published', r.published)
               order by e.start_date nulls last, e.name)
        from public.results r join public.exams e on e.id = r.exam_id
        where r.student_id = s.id and (v_staff or r.published)), '[]'::jsonb)
  ) into v
  from public.students s
  join public.profiles sp on sp.id = s.id
  left join public.classes c on c.id = s.class_id
  left join public.teachers ct on ct.id = c.class_teacher_id
  left join public.profiles ctp on ctp.id = ct.id
  left join public.profiles pp on pp.id = s.parent_id
  where s.id = p_student;

  if v is null then raise exception 'campusdesk:not_found' using errcode = 'P0001'; end if;
  return v;
end $$;

-- ---- from migrations/004_v2_results_integrity.sql ----
create or replace function public.exam_result_status(p_exam uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v_class uuid; v_expected int; v jsonb;
begin
  select class_id into v_class from public.exams where id = p_exam;
  if v_class is null then raise exception 'campusdesk:not_found' using errcode = 'P0001'; end if;
  if not (public.is_admin() or public.in_class(v_class) and public.get_my_role() = 'teacher') then
    raise exception 'campusdesk:not_allowed' using errcode = '42501';
  end if;
  select count(*) into v_expected from public.subjects where class_id = v_class;

  with per as (
    select s.id as student_id,
           (select count(distinct m.subject_id) from public.marks m
              join public.subjects sb on sb.id = m.subject_id and sb.class_id = v_class
             where m.student_id = s.id and m.exam_id = p_exam) as have,
           (select round(100.0 * sum(m.marks_obtained) / nullif(sum(m.max_marks), 0), 1) from public.marks m
              where m.student_id = s.id and m.exam_id = p_exam) as pct
    from public.students s where s.class_id = v_class)
  select jsonb_build_object(
      'exam_id', p_exam, 'expected_subjects', v_expected,
      'students', count(*),
      'evaluated', count(*) filter (where v_expected > 0 and have = v_expected),
      'incomplete', count(*) filter (where not (v_expected > 0 and have = v_expected)),
      'average', round(avg(pct) filter (where v_expected > 0 and have = v_expected), 1),
      'highest', max(pct) filter (where v_expected > 0 and have = v_expected),
      'lowest',  min(pct) filter (where v_expected > 0 and have = v_expected),
      'published', (select count(*) from public.results r where r.exam_id = p_exam and r.published))
  into v from per;
  return v;
end $$;

create or replace function public.publish_exam_results(p_exam uuid, p_allow_incomplete boolean default false)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_class uuid; v_expected int; v_status jsonb;
begin
  if not public.is_admin() then raise exception 'campusdesk:not_allowed' using errcode = '42501'; end if;
  select class_id into v_class from public.exams where id = p_exam;
  if v_class is null then raise exception 'campusdesk:not_found' using errcode = 'P0001'; end if;
  select count(*) into v_expected from public.subjects where class_id = v_class;
  if v_expected = 0 then raise exception 'campusdesk:no_subjects' using errcode = 'P0001'; end if;

  v_status := public.exam_result_status(p_exam);
  if (v_status->>'incomplete')::int > 0 and not p_allow_incomplete then
    raise exception 'campusdesk:incomplete_results' using errcode = 'P0001', detail = v_status::text;
  end if;

  -- evaluated students: compute and publish
  insert into public.results (student_id, exam_id, total_marks, percentage, grade, rank, published)
  select t.student_id, p_exam, t.total, t.pct, public.grade_for(t.pct),
         (rank() over (order by t.pct desc))::int, true
  from (
    select m.student_id, sum(m.marks_obtained) as total,
           round(100.0 * sum(m.marks_obtained) / nullif(sum(m.max_marks), 0), 1) as pct
    from public.marks m
    join public.students s on s.id = m.student_id and s.class_id = v_class
    where m.exam_id = p_exam
    group by m.student_id
    having count(distinct m.subject_id) filter (where m.subject_id in (select id from public.subjects where class_id = v_class)) = v_expected
  ) t
  on conflict (student_id, exam_id) do update
    set total_marks = excluded.total_marks, percentage = excluded.percentage, grade = excluded.grade,
        rank = excluded.rank, published = true;

  -- incomplete students: make sure no (possibly stale/zero) result is visible. Rows are kept, just hidden.
  update public.results r set published = false, rank = null
   where r.exam_id = p_exam and r.published
     and r.student_id in (select s.id from public.students s where s.class_id = v_class)
     and not exists (
        select 1 from public.marks m where m.student_id = r.student_id and m.exam_id = p_exam
        group by m.student_id having count(distinct m.subject_id) = v_expected);

  insert into public.audit_logs (actor_id, action, target_table, target_id, details)
  values (auth.uid(), 'publish_results', 'exams', p_exam,
          v_status || jsonb_build_object('allow_incomplete', p_allow_incomplete));
  return public.exam_result_status(p_exam);
end $$;

create or replace function public.unpublish_exam_results(p_exam uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'campusdesk:not_allowed' using errcode = '42501'; end if;
  update public.results set published = false where exam_id = p_exam;
  insert into public.audit_logs (actor_id, action, target_table, target_id, details)
  values (auth.uid(), 'unpublish_results', 'exams', p_exam, '{}'::jsonb);
end $$;

create or replace function public.class_exam_averages(p_class uuid)
returns table (exam_id uuid, exam_name text, exam_date date, subject_name text, avg_pct numeric, students int)
language sql stable security definer set search_path = public as $$
  select e.id, e.name, e.start_date, s.name,
         round(avg(m.marks_obtained * 100.0 / m.max_marks), 1),
         count(distinct m.student_id)::int
  from public.marks m
  join public.exams e    on e.id = m.exam_id
  join public.subjects s on s.id = m.subject_id
  join public.results r  on r.student_id = m.student_id and r.exam_id = m.exam_id and r.published
  where e.class_id = p_class
    and (public.is_admin() or public.in_class(p_class))
  group by e.id, e.name, e.start_date, s.name
  having count(distinct m.student_id) >= 2;     -- never an "average" of one identifiable student
$$;
grant execute on function public.class_exam_averages(uuid) to authenticated;

-- ---- from migrations/005_v2_notifications.sql ----
create or replace function public.is_seeding()
returns boolean language sql stable as $$
  select coalesce(current_setting('campusdesk.seeding', true), '') = 'on';
$$;

create or replace function public.push_notification(p_user uuid, p_type text, p_title text, p_body text, p_link text)
returns void language sql security definer set search_path = public as $$
  insert into public.notifications (user_id, type, title, body, link)
  select p_user, p_type, p_title, p_body, p_link
  where p_user is not null and exists (select 1 from public.profiles where id = p_user and status = 'active');
$$;

create or replace function public.notify_student_and_parent(p_student uuid, p_type text, p_title text, p_body text, p_link text)
returns void language plpgsql security definer set search_path = public as $$
declare v_parent uuid;
begin
  select parent_id into v_parent from public.students where id = p_student;
  perform public.push_notification(p_student, p_type, p_title, p_body, p_link);
  perform public.push_notification(v_parent,  p_type, p_title, p_body, p_link);
end $$;

create or replace function public.trg_notice_notify()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if public.is_seeding() then return new; end if;
  insert into public.notifications (user_id, type, title, body, link)
  select p.id, 'notice', 'New notice: ' || new.title, left(coalesce(new.content, ''), 140), '/notices'
  from public.profiles p
  where p.status = 'active' and p.id is distinct from new.posted_by
    and (new.target_role = 'all' or new.target_role = p.role || 's')
    and (new.target_class_id is null
         or exists (select 1 from public.students s where s.class_id = new.target_class_id and (s.id = p.id or s.parent_id = p.id))
         or exists (select 1 from public.teacher_subjects ts where ts.class_id = new.target_class_id and ts.teacher_id = p.id)
         or p.role = 'admin');
  insert into public.audit_logs (actor_id, action, target_table, target_id, details)
  values (new.posted_by, 'post_notice', 'notices', new.id, jsonb_build_object('title', new.title));
  return new;
end $$;

create or replace function public.trg_result_notify()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_exam text;
begin
  if public.is_seeding() then return new; end if;
  if new.published and (tg_op = 'INSERT' or coalesce(old.published, false) = false) then
    select name into v_exam from public.exams where id = new.exam_id;
    perform public.notify_student_and_parent(new.student_id, 'result', 'Result published: ' || coalesce(v_exam, 'exam'),
      'Your result is now available.', '/results');
  end if;
  return new;
end $$;

create or replace function public.trg_fee_notify()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_name text;
begin
  if public.is_seeding() then return new; end if;
  select full_name into v_name from public.profiles where id = new.student_id;
  if tg_op = 'INSERT' and new.status = 'pending_verification' then
    insert into public.notifications (user_id, type, title, body, link)
    select p.id, 'fee', 'Payment awaiting verification',
           coalesce(v_name, 'A student') || ' submitted INR ' || new.amount_paid::text, '/fees'
    from public.profiles p where p.role = 'admin' and p.status = 'active';
    perform public.push_notification(new.student_id, 'fee', 'Payment submitted',
            'INR ' || new.amount_paid::text || ' is awaiting verification by the school office.', '/fees');
  elsif tg_op = 'UPDATE' and new.status is distinct from old.status then
    if new.status in ('paid','partial') then
      perform public.notify_student_and_parent(new.student_id, 'fee', 'Payment verified',
        'INR ' || new.amount_paid::text || ' was confirmed. Receipt ' || coalesce(new.receipt_no, '-') || '.', '/fees');
    elsif new.status = 'rejected' then
      perform public.notify_student_and_parent(new.student_id, 'fee', 'Payment rejected',
        coalesce(nullif(new.rejection_reason, ''), 'A submitted payment could not be verified.') || ' You can submit it again.', '/fees');
    end if;
  end if;
  return new;
end $$;

create or replace function public.trg_leave_notify()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_name text;
begin
  if public.is_seeding() then return new; end if;
  if tg_op = 'INSERT' then
    select full_name into v_name from public.profiles where id = new.requester_id;
    insert into public.notifications (user_id, type, title, body, link)
    select p.id, 'leave', 'New leave request',
           coalesce(v_name, 'A user') || ' requested leave from ' || new.from_date::text || ' to ' || new.to_date::text, '/leave'
    from public.profiles p where p.role = 'admin' and p.status = 'active';
    insert into public.audit_logs (actor_id, action, target_table, target_id, details)
    values (new.requester_id, 'request_leave', 'leave_requests', new.id, jsonb_build_object('requester', v_name));
  elsif new.status is distinct from old.status and new.status in ('approved','rejected') then
    perform public.push_notification(new.requester_id, 'leave', 'Leave request ' || new.status,
      'Your leave from ' || new.from_date::text || ' to ' || new.to_date::text || ' was ' || new.status ||
      case when new.status = 'rejected' and new.rejection_reason is not null then ': ' || new.rejection_reason else '.' end, '/leave');
  end if;
  return new;
end $$;

create or replace function public.trg_timetable_notify()
returns trigger language plpgsql security definer set search_path = public as $$
declare r public.timetable; v_subject text; v_verb text;
begin
  if public.is_seeding() then return coalesce(new, old); end if;
  r := case when tg_op = 'DELETE' then old else new end;
  v_verb := case tg_op when 'INSERT' then 'added to' when 'UPDATE' then 'changed in' else 'removed from' end;
  select name into v_subject from public.subjects where id = r.subject_id;
  insert into public.notifications (user_id, type, title, body, link)
  select distinct u.uid, 'timetable', 'Timetable updated', coalesce(v_subject, 'A period') || ' was ' || v_verb || ' the timetable.', '/timetable'
  from (select s.id as uid from public.students s where s.class_id = r.class_id
        union select s.parent_id from public.students s where s.class_id = r.class_id and s.parent_id is not null
        union select r.teacher_id where r.teacher_id is not null) u
  where u.uid is distinct from auth.uid()
    and exists (select 1 from public.profiles pr where pr.id = u.uid and pr.status = 'active');
  insert into public.audit_logs (actor_id, action, target_table, target_id, details)
  values (auth.uid(), 'timetable_' || lower(tg_op), 'timetable', r.id, jsonb_build_object('subject', v_subject));
  return coalesce(new, old);
end $$;

create or replace function public.trg_event_notify()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if public.is_seeding() then return new; end if;
  insert into public.notifications (user_id, type, title, body, link)
  select p.id, 'event', 'New event: ' || new.title, to_char(new.event_date, 'DD Mon YYYY'), '/events'
  from public.profiles p where p.status = 'active' and p.id is distinct from new.created_by;
  return new;
end $$;

create or replace function public.trg_query_notify()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if public.is_seeding() then return new; end if;
  if tg_op = 'INSERT' then
    perform public.push_notification(new.teacher_id, 'query', 'New student query', left(new.message, 120), '/chat');
  elsif new.status = 'answered' and old.status is distinct from 'answered' then
    perform public.push_notification(new.sender_id, 'query', 'Your query was answered', left(coalesce(new.reply, ''), 120), '/chat');
  end if;
  return new;
end $$;

-- Attendance alert: tell student + parent when a student is marked absent.
create or replace function public.trg_attendance_notify()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_subject text;
begin
  if public.is_seeding() then return new; end if;
  if new.status = 'absent' and (tg_op = 'INSERT' or old.status is distinct from 'absent') then
    select name into v_subject from public.subjects where id = new.subject_id;
    perform public.notify_student_and_parent(new.student_id, 'attendance', 'Marked absent',
      'Absent in ' || coalesce(v_subject, 'class') || ' on ' || to_char(new.date, 'DD Mon YYYY') || '.', '/attendance');
  end if;
  return new;
end $$;

-- ---- from migrations/006_v2_leave_attendance_timetable.sql ----
create or replace function public.leave_requests_guard()
returns trigger language plpgsql as $$
begin
  if new.to_date < new.from_date then raise exception 'campusdesk:invalid_dates' using errcode = 'P0001'; end if;
  if tg_op = 'INSERT' then
    if new.from_date < current_date - 30 then raise exception 'campusdesk:leave_too_old' using errcode = 'P0001'; end if;
    if exists (select 1 from public.leave_requests l
               where l.requester_id = new.requester_id and l.status in ('pending','approved')
                 and l.from_date <= new.to_date and l.to_date >= new.from_date) then
      raise exception 'campusdesk:leave_overlap' using errcode = 'P0001';
    end if;
  elsif new.status is distinct from old.status and new.status in ('approved','rejected') then
    new.decided_at := now();
  end if;
  return new;
end $$;

create or replace function public.timetable_conflict_guard()
returns trigger language plpgsql as $$
begin
  if new.end_time <= new.start_time then raise exception 'campusdesk:invalid_times' using errcode = 'P0001'; end if;
  if exists (select 1 from public.timetable t
             where t.id is distinct from new.id and t.day_of_week = new.day_of_week
               and t.start_time < new.end_time and t.end_time > new.start_time
               and t.class_id = new.class_id) then
    raise exception 'campusdesk:class_conflict' using errcode = 'P0001';
  end if;
  if new.teacher_id is not null and exists (select 1 from public.timetable t
             where t.id is distinct from new.id and t.day_of_week = new.day_of_week
               and t.start_time < new.end_time and t.end_time > new.start_time
               and t.teacher_id = new.teacher_id) then
    raise exception 'campusdesk:teacher_conflict' using errcode = 'P0001';
  end if;
  return new;
end $$;

-- Save a whole roster atomically. p_rows = [{"student_id": "...", "status": "present|late|absent|leave"}]
create or replace function public.save_attendance(p_class uuid, p_subject uuid, p_date date, p_rows jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare r record; v_updated int := 0; v_inserted int := 0; n int;
begin
  if not (public.is_admin() or exists (select 1 from public.teacher_subjects ts
          where ts.teacher_id = auth.uid() and ts.class_id = p_class and ts.subject_id = p_subject)) then
    raise exception 'campusdesk:not_allowed' using errcode = '42501';
  end if;
  if p_date > current_date then raise exception 'campusdesk:future_date' using errcode = 'P0001'; end if;
  for r in select (x->>'student_id')::uuid as sid, x->>'status' as st from jsonb_array_elements(p_rows) x loop
    if r.st not in ('present','late','absent','leave') then raise exception 'campusdesk:invalid_status' using errcode = 'P0001'; end if;
    if not exists (select 1 from public.students where id = r.sid and class_id = p_class) then
      raise exception 'campusdesk:student_not_in_class' using errcode = 'P0001';
    end if;
    update public.attendance set status = r.st, marked_by = auth.uid(), class_id = p_class
     where student_id = r.sid and subject_id = p_subject and date = p_date;
    get diagnostics n = row_count;
    if n = 0 then
      insert into public.attendance (student_id, class_id, subject_id, date, status, marked_by)
      values (r.sid, p_class, p_subject, p_date, r.st, auth.uid());
      v_inserted := v_inserted + 1;
    else v_updated := v_updated + n; end if;
  end loop;
  return jsonb_build_object('inserted', v_inserted, 'updated', v_updated);
end $$;

-- Aggregated counts (admin: any class; teacher: only classes they teach).
create or replace function public.attendance_summary_by_class(p_class uuid default null)
returns table (class_id uuid, subject_id uuid, present bigint, late bigint, absent bigint, leave_count bigint)
language plpgsql stable security definer set search_path = public as $$
begin
  if not (public.is_admin() or public.get_my_role() = 'teacher') then
    raise exception 'campusdesk:not_allowed' using errcode = '42501';
  end if;
  return query
  select a.class_id, a.subject_id,
         count(*) filter (where a.status = 'present'), count(*) filter (where a.status = 'late'),
         count(*) filter (where a.status = 'absent'),  count(*) filter (where a.status = 'leave')
  from public.attendance a
  where (p_class is null or a.class_id = p_class)
    and (public.is_admin()
         or exists (select 1 from public.teacher_subjects ts where ts.teacher_id = auth.uid() and ts.class_id = a.class_id)
         or exists (select 1 from public.classes c where c.id = a.class_id and c.class_teacher_id = auth.uid()))
  group by a.class_id, a.subject_id;
end $$;

-- ---- from migrations/008_v2_auth_account_management.sql ----
create or replace function public.is_active_user()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and status = 'active');
$$;

create or replace function public.get_my_role()
returns text language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid() and status = 'active';
$$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin' and status = 'active');
$$;

-- ID-assigning triggers run with owner rights so a legitimate insert never fails on sequence privileges
-- (003 defined them without SECURITY DEFINER; behaviour is otherwise identical).
create or replace function public.assign_student_code()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.student_code is null then
    new.student_code := 'STU-' || to_char(coalesce(new.admission_date, current_date), 'YYYY') || '-' || to_char(nextval('public.student_code_seq'), 'FM000');
  end if;
  return new;
end $$;

create or replace function public.assign_teacher_code()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.teacher_code is null then
    new.teacher_code := 'TCH-' || to_char(coalesce(new.joining_date, current_date), 'YYYY') || '-' || to_char(nextval('public.teacher_code_seq'), 'FM000');
  end if;
  return new;
end $$;

-- Every new Auth user becomes a PENDING profile. Client-supplied role/status are never used.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_req text; v_role text := 'student'; v_status text := 'pending'; v_legacy boolean := false;
  v_name text := nullif(trim(coalesce(new.raw_user_meta_data->>'full_name', '')), '');
begin
  v_req := lower(nullif(trim(coalesce(new.raw_user_meta_data->>'requested_role', '')), ''));
  if v_req is null or v_req not in ('student','parent','teacher') then v_req := null; end if;   -- 'admin' etc. ignored

  select coalesce(value = 'true', false) into v_legacy from public.campusdesk_settings where key = 'allow_legacy_signup_role';
  if coalesce(v_legacy, false) and lower(coalesce(new.raw_user_meta_data->>'role', '')) in ('student','parent','teacher') then
    v_role := lower(new.raw_user_meta_data->>'role'); v_status := 'active'; v_req := coalesce(v_req, v_role);   -- opt-in V1 behaviour, never admin
  end if;

  insert into public.profiles (id, role, status, full_name, email, phone, requested_role)
  values (new.id, v_role, v_status, v_name, new.email, nullif(trim(coalesce(new.raw_user_meta_data->>'phone', '')), ''), v_req)
  on conflict (id) do nothing;

  if v_status = 'pending' and not public.is_seeding() then
    insert into public.notifications (user_id, type, title, body, link)
    select p.id, 'account', 'New registration request',
           coalesce(v_name, new.email) || ' registered' || coalesce(' and requested a ' || v_req || ' account', '') || '.',
           '/account-requests'
    from public.profiles p where p.role = 'admin' and p.status = 'active';
    insert into public.audit_logs (actor_id, action, target_table, target_id, details)
    values (new.id, 'account_registered', 'profiles', new.id, jsonb_build_object('requested_role', v_req, 'email', new.email));
  end if;
  return new;
end $$;

-- Only administrators may change identity / role / approval fields, or create profiles from a client.
create or replace function public.guard_profile_update()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then return new; end if;           -- SQL editor, service role, auth trigger
  if public.is_admin() then return new; end if;
  if tg_op = 'INSERT' then raise exception 'campusdesk:role_locked' using errcode = '42501'; end if;
  if new.id is distinct from old.id or new.role is distinct from old.role or new.status is distinct from old.status
     or new.requested_role is distinct from old.requested_role or new.decided_by is distinct from old.decided_by
     or new.decided_at is distinct from old.decided_at or new.rejection_reason is distinct from old.rejection_reason
     or new.status_reason is distinct from old.status_reason then
    raise exception 'campusdesk:role_locked' using errcode = '42501';
  end if;
  return new;
end $$;

-- State of the logged-in account (works for pending/suspended users; they cannot read other tables)
create or replace function public.my_account_state()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare p public.profiles; v_ok boolean := true;
begin
  if auth.uid() is null then return jsonb_build_object('exists', false); end if;
  select * into p from public.profiles where id = auth.uid();
  if not found then return jsonb_build_object('exists', false); end if;
  if p.role = 'student' then v_ok := exists (select 1 from public.students where id = p.id);
  elsif p.role = 'teacher' then v_ok := exists (select 1 from public.teachers where id = p.id); end if;
  return jsonb_build_object('exists', true, 'status', p.status, 'role', p.role, 'requested_role', p.requested_role,
    'full_name', p.full_name, 'email', p.email, 'rejection_reason', p.rejection_reason,
    'status_reason', p.status_reason, 'entity_ok', v_ok, 'created_at', p.created_at);
end $$;

create or replace function public.admin_account_counts()
returns jsonb language plpgsql stable security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'campusdesk:not_allowed' using errcode = '42501'; end if;
  return (select jsonb_build_object(
    'total', count(*),
    'pending', count(*) filter (where status = 'pending'), 'active', count(*) filter (where status = 'active'),
    'suspended', count(*) filter (where status = 'suspended'), 'rejected', count(*) filter (where status = 'rejected'),
    'incomplete', count(*) filter (where status = 'incomplete'),
    'students', count(*) filter (where status = 'active' and role = 'student'),
    'teachers', count(*) filter (where status = 'active' and role = 'teacher'),
    'parents',  count(*) filter (where status = 'active' and role = 'parent'),
    'admins',   count(*) filter (where status = 'active' and role = 'admin')) from public.profiles);
end $$;

create or replace function public.admin_list_accounts(
  p_status text default null, p_role text default null, p_search text default null,
  p_limit int default 50, p_offset int default 0)
returns table (id uuid, full_name text, email text, phone text, role text, requested_role text, status text,
               created_at timestamptz, decided_at timestamptz, rejection_reason text,
               entity_code text, entity_detail text, total_count bigint)
language plpgsql stable security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'campusdesk:not_allowed' using errcode = '42501'; end if;
  return query
  select p.id, p.full_name, p.email, p.phone, p.role, p.requested_role, p.status, p.created_at, p.decided_at, p.rejection_reason,
         coalesce(s.student_code, t.teacher_code, t.employee_id),
         case when p.status in ('pending','rejected') then null
              when p.role = 'student' and s.id is not null then coalesce('Class ' || c.name || '-' || c.section, 'No class')
              when p.role = 'teacher' and t.id is not null then coalesce(t.department, 'No department')
              when p.role = 'parent' then (select count(*)::text || ' child(ren)' from public.students k where k.parent_id = p.id)
              else null end,
         count(*) over ()
  from public.profiles p
  left join public.students s on s.id = p.id
  left join public.classes c on c.id = s.class_id
  left join public.teachers t on t.id = p.id
  where (p_status is null or p.status = p_status)
    and (p_role is null or case when p.status in ('pending','rejected') then p.requested_role = p_role else p.role = p_role end)
    and (p_search is null or p_search = '' or p.full_name ilike '%' || p_search || '%' or p.email ilike '%' || p_search || '%'
         or p.phone ilike '%' || p_search || '%' or s.student_code ilike '%' || p_search || '%' or s.roll_no ilike '%' || p_search || '%'
         or t.teacher_code ilike '%' || p_search || '%' or t.employee_id ilike '%' || p_search || '%')
  order by (p.status = 'pending') desc, p.created_at desc nulls last
  limit least(greatest(p_limit, 1), 200) offset greatest(p_offset, 0);
end $$;

create or replace function public.admin_get_account(p_user uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v jsonb;
begin
  if not public.is_admin() then raise exception 'campusdesk:not_allowed' using errcode = '42501'; end if;
  select jsonb_build_object(
    'id', p.id, 'full_name', p.full_name, 'email', p.email, 'phone', p.phone, 'role', p.role, 'status', p.status,
    'requested_role', p.requested_role, 'created_at', p.created_at, 'decided_at', p.decided_at,
    'rejection_reason', p.rejection_reason, 'status_reason', p.status_reason,
    'decided_by_name', (select full_name from public.profiles where id = p.decided_by),
    'student', (select to_jsonb(s) from public.students s where s.id = p.id),
    'teacher', (select to_jsonb(t) from public.teachers t where t.id = p.id),
    'children', coalesce((select jsonb_agg(jsonb_build_object('id', k.id, 'name', kp.full_name, 'roll_no', k.roll_no,
                 'class', c.name || '-' || c.section)) from public.students k join public.profiles kp on kp.id = k.id
                 left join public.classes c on c.id = k.class_id where k.parent_id = p.id), '[]'::jsonb),
    'assignments', coalesce((select jsonb_agg(jsonb_build_object('class_id', ts.class_id, 'subject_id', ts.subject_id,
                 'class', c.name || '-' || c.section, 'subject', sb.name)) from public.teacher_subjects ts
                 join public.classes c on c.id = ts.class_id join public.subjects sb on sb.id = ts.subject_id
                 where ts.teacher_id = p.id), '[]'::jsonb),
    'class_teacher_of', coalesce((select jsonb_agg(c.id) from public.classes c where c.class_teacher_id = p.id), '[]'::jsonb)
  ) into v from public.profiles p where p.id = p_user;
  if v is null then raise exception 'campusdesk:not_found' using errcode = 'P0001'; end if;
  return v;
end $$;

-- APPROVE / PROVISION. One transaction: any failure rolls back everything (no half-provisioned accounts).
--   p_activate = true  -> validates required fields, creates entity + relationships, status 'active'
--   p_activate = false -> role assigned, whatever was supplied is saved, status 'incomplete'
-- p_data keys. student: roll_no, class_id, dob, gender, address, admission_date, parent_id
--              parent : child_ids [uuid]       teacher: employee_id, department, qualification, joining_date,
--                       assignments [{class_id, subject_id}], class_teacher_of [class_id]
create or replace function public.admin_provision_account(
  p_user uuid, p_role text, p_data jsonb default '{}'::jsonb, p_activate boolean default true)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_admin uuid := auth.uid(); p public.profiles; v_prev_status text; v_prev_role text;
  v_roll text; v_class uuid; v_parent uuid; v_emp text; v_dept text; v_child uuid; v_children uuid[]; v_a jsonb; v_cid uuid;
  v_new_status text := case when p_activate then 'active' else 'incomplete' end;
begin
  if not public.is_admin() then raise exception 'campusdesk:not_allowed' using errcode = '42501'; end if;
  p_data := coalesce(p_data, '{}'::jsonb);
  select * into p from public.profiles where id = p_user for update;
  if not found then raise exception 'campusdesk:not_found' using errcode = 'P0001'; end if;
  if p_user = v_admin then raise exception 'campusdesk:cannot_modify_self' using errcode = 'P0001'; end if;
  if p.role = 'admin' and p.status in ('active','suspended') then raise exception 'campusdesk:use_admin_tools' using errcode = 'P0001'; end if;
  if p_role not in ('student','parent','teacher') then raise exception 'campusdesk:invalid_role' using errcode = 'P0001'; end if;
  v_prev_status := p.status; v_prev_role := p.role;

  -- changing the role of an account that already has records would orphan data: block it
  if p.status in ('active','suspended','incomplete') and p.role <> p_role then
    if (p.role = 'student' and (exists (select 1 from public.attendance where student_id = p.id) or exists (select 1 from public.marks where student_id = p.id)
                                or exists (select 1 from public.fee_payments where student_id = p.id)))
       or (p.role = 'teacher' and (exists (select 1 from public.teacher_subjects where teacher_id = p.id) or exists (select 1 from public.timetable where teacher_id = p.id)
                                   or exists (select 1 from public.classes where class_teacher_id = p.id)))
       or (p.role = 'parent' and exists (select 1 from public.students where parent_id = p.id)) then
      raise exception 'campusdesk:role_change_blocked' using errcode = 'P0001';
    end if;
  end if;

  if p_role = 'student' then
    v_roll := nullif(trim(p_data->>'roll_no'), ''); v_class := nullif(p_data->>'class_id', '')::uuid;
    v_parent := nullif(p_data->>'parent_id', '')::uuid;
    if p_activate and (v_roll is null and not exists (select 1 from public.students where id = p_user and roll_no is not null)
                       or v_class is null and not exists (select 1 from public.students where id = p_user and class_id is not null)) then
      raise exception 'campusdesk:student_fields_required' using errcode = 'P0001'; end if;
    if v_class is not null and not exists (select 1 from public.classes where id = v_class) then raise exception 'campusdesk:class_not_found' using errcode = 'P0001'; end if;
    if v_parent is not null and not exists (select 1 from public.profiles where id = v_parent and role = 'parent') then raise exception 'campusdesk:parent_not_found' using errcode = 'P0001'; end if;
    if v_roll is not null and exists (select 1 from public.students where roll_no = v_roll and id <> p_user) then raise exception 'campusdesk:roll_exists' using errcode = 'P0001'; end if;
    insert into public.students (id, roll_no, class_id, dob, gender, address, admission_date, parent_id)
    values (p_user, v_roll, v_class, nullif(p_data->>'dob', '')::date, nullif(p_data->>'gender', ''), nullif(p_data->>'address', ''),
            coalesce(nullif(p_data->>'admission_date', '')::date, current_date), v_parent)
    on conflict (id) do update set
      roll_no = case when p_data ? 'roll_no' then v_roll else public.students.roll_no end,
      class_id = case when p_data ? 'class_id' then v_class else public.students.class_id end,
      dob = case when p_data ? 'dob' then nullif(p_data->>'dob', '')::date else public.students.dob end,
      gender = case when p_data ? 'gender' then nullif(p_data->>'gender', '') else public.students.gender end,
      address = case when p_data ? 'address' then nullif(p_data->>'address', '') else public.students.address end,
      admission_date = case when p_data ? 'admission_date' then coalesce(nullif(p_data->>'admission_date', '')::date, public.students.admission_date) else public.students.admission_date end,
      parent_id = case when p_data ? 'parent_id' then v_parent else public.students.parent_id end;
    insert into public.audit_logs (actor_id, action, target_table, target_id, details)
    values (v_admin, 'student_provisioned', 'students', p_user, jsonb_build_object('roll_no', v_roll, 'class_id', v_class, 'parent_id', v_parent));
    if v_parent is not null then
      insert into public.audit_logs (actor_id, action, target_table, target_id, details) values (v_admin, 'parent_linked', 'students', p_user, jsonb_build_object('parent_id', v_parent));
    end if;

  elsif p_role = 'parent' then
    if p_data ? 'child_ids' then
      select coalesce(array_agg(x::uuid), '{}') into v_children from jsonb_array_elements_text(p_data->'child_ids') x;
    else
      select coalesce(array_agg(id), '{}') into v_children from public.students where parent_id = p_user;
    end if;
    if p_activate and cardinality(v_children) = 0 then raise exception 'campusdesk:parent_children_required' using errcode = 'P0001'; end if;
    foreach v_child in array v_children loop
      if not exists (select 1 from public.students where id = v_child) then raise exception 'campusdesk:child_not_found' using errcode = 'P0001'; end if;
      if exists (select 1 from public.students where id = v_child and parent_id is not null and parent_id <> p_user) then raise exception 'campusdesk:child_has_parent' using errcode = 'P0001'; end if;
      update public.students set parent_id = p_user where id = v_child and parent_id is distinct from p_user;
      if found then insert into public.audit_logs (actor_id, action, target_table, target_id, details) values (v_admin, 'parent_linked', 'students', v_child, jsonb_build_object('parent_id', p_user)); end if;
    end loop;
    if p_data ? 'child_ids' then
      update public.students set parent_id = null where parent_id = p_user and not (id = any (v_children));
    end if;

  elsif p_role = 'teacher' then
    v_emp := nullif(trim(p_data->>'employee_id'), ''); v_dept := nullif(trim(p_data->>'department'), '');
    if p_activate and (v_emp is null and not exists (select 1 from public.teachers where id = p_user and employee_id is not null)
                       or v_dept is null and not exists (select 1 from public.teachers where id = p_user and department is not null)) then
      raise exception 'campusdesk:teacher_fields_required' using errcode = 'P0001'; end if;
    if v_emp is not null and exists (select 1 from public.teachers where employee_id = v_emp and id <> p_user) then raise exception 'campusdesk:employee_exists' using errcode = 'P0001'; end if;
    insert into public.teachers (id, employee_id, department, qualification, joining_date)
    values (p_user, v_emp, v_dept, nullif(p_data->>'qualification', ''), nullif(p_data->>'joining_date', '')::date)
    on conflict (id) do update set
      employee_id = case when p_data ? 'employee_id' then v_emp else public.teachers.employee_id end,
      department = case when p_data ? 'department' then v_dept else public.teachers.department end,
      qualification = case when p_data ? 'qualification' then nullif(p_data->>'qualification', '') else public.teachers.qualification end,
      joining_date = case when p_data ? 'joining_date' then nullif(p_data->>'joining_date', '')::date else public.teachers.joining_date end;

    if p_data ? 'assignments' then
      for v_a in select * from jsonb_array_elements(p_data->'assignments') loop
        if not exists (select 1 from public.subjects where id = (v_a->>'subject_id')::uuid and class_id = (v_a->>'class_id')::uuid) then
          raise exception 'campusdesk:invalid_assignment' using errcode = 'P0001'; end if;
      end loop;
      delete from public.teacher_subjects ts where ts.teacher_id = p_user and not exists (
        select 1 from jsonb_array_elements(p_data->'assignments') a
         where (a->>'class_id')::uuid = ts.class_id and (a->>'subject_id')::uuid = ts.subject_id);
      insert into public.teacher_subjects (teacher_id, subject_id, class_id)
      select p_user, (a->>'subject_id')::uuid, (a->>'class_id')::uuid from jsonb_array_elements(p_data->'assignments') a
       where not exists (select 1 from public.teacher_subjects ts where ts.teacher_id = p_user
                         and ts.class_id = (a->>'class_id')::uuid and ts.subject_id = (a->>'subject_id')::uuid);
    end if;
    if p_data ? 'class_teacher_of' then
      for v_cid in select x::uuid from jsonb_array_elements_text(p_data->'class_teacher_of') x loop
        if not exists (select 1 from public.classes where id = v_cid) then raise exception 'campusdesk:class_not_found' using errcode = 'P0001'; end if;
        if exists (select 1 from public.classes where id = v_cid and class_teacher_id is not null and class_teacher_id <> p_user) then raise exception 'campusdesk:class_has_teacher' using errcode = 'P0001'; end if;
        update public.classes set class_teacher_id = p_user where id = v_cid;
      end loop;
      update public.classes set class_teacher_id = null where class_teacher_id = p_user
         and id not in (select x::uuid from jsonb_array_elements_text(p_data->'class_teacher_of') x);
    end if;
    insert into public.audit_logs (actor_id, action, target_table, target_id, details)
    values (v_admin, 'teacher_provisioned', 'teachers', p_user, jsonb_build_object('employee_id', v_emp, 'department', v_dept));
  end if;

  update public.profiles set role = p_role, status = v_new_status, decided_by = v_admin, decided_at = now(),
         rejection_reason = null, status_reason = null where id = p_user;

  if v_prev_role is distinct from p_role or v_prev_status in ('pending','rejected') then
    insert into public.audit_logs (actor_id, action, target_table, target_id, details)
    values (v_admin, 'role_assigned', 'profiles', p_user, jsonb_build_object('role', p_role, 'requested_role', p.requested_role));
  end if;
  insert into public.audit_logs (actor_id, action, target_table, target_id, details)
  values (v_admin, case when p_activate then 'account_approved' else 'account_setup_incomplete' end, 'profiles', p_user,
          jsonb_build_object('role', p_role, 'previous_status', v_prev_status));
  if v_prev_status is distinct from v_new_status then
    insert into public.notifications (user_id, type, title, body, link)
    values (p_user, 'account',
            case when p_activate then 'Your CampusDesk account has been approved' else 'Your account setup is not finished yet' end,
            case when p_activate then 'You can now use CampusDesk as a ' || p_role || '.' else 'An administrator still needs to complete your ' || p_role || ' details.' end, '/');
  end if;
  return jsonb_build_object('id', p_user, 'role', p_role, 'status', v_new_status);
end $$;

create or replace function public.admin_reject_account(p_user uuid, p_reason text default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare p public.profiles;
begin
  if not public.is_admin() then raise exception 'campusdesk:not_allowed' using errcode = '42501'; end if;
  select * into p from public.profiles where id = p_user for update;
  if not found then raise exception 'campusdesk:not_found' using errcode = 'P0001'; end if;
  if p_user = auth.uid() then raise exception 'campusdesk:cannot_modify_self' using errcode = 'P0001'; end if;
  if p.status not in ('pending','incomplete') then raise exception 'campusdesk:not_rejectable' using errcode = 'P0001'; end if;
  update public.profiles set status = 'rejected', rejection_reason = nullif(trim(coalesce(p_reason, '')), ''),
         decided_by = auth.uid(), decided_at = now() where id = p_user;
  insert into public.audit_logs (actor_id, action, target_table, target_id, details)
  values (auth.uid(), 'account_rejected', 'profiles', p_user, jsonb_build_object('reason', p_reason));
  insert into public.notifications (user_id, type, title, body, link)
  values (p_user, 'account', 'Your CampusDesk registration was not approved', coalesce(nullif(trim(coalesce(p_reason, '')), ''), 'Please contact the school office.'), '/');
  return jsonb_build_object('id', p_user, 'status', 'rejected');
end $$;

create or replace function public.admin_suspend_account(p_user uuid, p_reason text default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare p public.profiles;
begin
  if not public.is_admin() then raise exception 'campusdesk:not_allowed' using errcode = '42501'; end if;
  select * into p from public.profiles where id = p_user for update;
  if not found then raise exception 'campusdesk:not_found' using errcode = 'P0001'; end if;
  if p_user = auth.uid() then raise exception 'campusdesk:cannot_modify_self' using errcode = 'P0001'; end if;
  if p.status <> 'active' then raise exception 'campusdesk:not_active' using errcode = 'P0001'; end if;
  if p.role = 'admin' and not exists (select 1 from public.profiles where role = 'admin' and status = 'active' and id <> p_user) then
    raise exception 'campusdesk:last_admin' using errcode = 'P0001'; end if;
  update public.profiles set status = 'suspended', status_reason = nullif(trim(coalesce(p_reason, '')), ''), decided_by = auth.uid(), decided_at = now() where id = p_user;
  insert into public.audit_logs (actor_id, action, target_table, target_id, details) values (auth.uid(), 'account_suspended', 'profiles', p_user, jsonb_build_object('reason', p_reason));
  insert into public.notifications (user_id, type, title, body, link) values (p_user, 'account', 'Your account has been suspended', coalesce(nullif(trim(coalesce(p_reason, '')), ''), 'Contact the school office for details.'), '/');
  return jsonb_build_object('id', p_user, 'status', 'suspended');
end $$;

create or replace function public.admin_reactivate_account(p_user uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
declare p public.profiles; v_status text := 'active';
begin
  if not public.is_admin() then raise exception 'campusdesk:not_allowed' using errcode = '42501'; end if;
  select * into p from public.profiles where id = p_user for update;
  if not found then raise exception 'campusdesk:not_found' using errcode = 'P0001'; end if;
  if p.status <> 'suspended' then raise exception 'campusdesk:not_suspended' using errcode = 'P0001'; end if;
  if (p.role = 'student' and not exists (select 1 from public.students where id = p_user))
     or (p.role = 'teacher' and not exists (select 1 from public.teachers where id = p_user)) then v_status := 'incomplete'; end if;
  update public.profiles set status = v_status, status_reason = null, decided_by = auth.uid(), decided_at = now() where id = p_user;
  insert into public.audit_logs (actor_id, action, target_table, target_id, details) values (auth.uid(), 'account_reactivated', 'profiles', p_user, jsonb_build_object('status', v_status));
  insert into public.notifications (user_id, type, title, body, link) values (p_user, 'account', 'Your account has been reactivated', 'You can log in again.', '/');
  return jsonb_build_object('id', p_user, 'status', v_status);
end $$;

-- The ONLY way to create an administrator: an existing active admin promotes an existing active account.
create or replace function public.admin_promote_to_admin(p_user uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
declare p public.profiles;
begin
  if not public.is_admin() then raise exception 'campusdesk:not_allowed' using errcode = '42501'; end if;
  select * into p from public.profiles where id = p_user for update;
  if not found then raise exception 'campusdesk:not_found' using errcode = 'P0001'; end if;
  if p.status <> 'active' then raise exception 'campusdesk:not_active' using errcode = 'P0001'; end if;
  if p.role = 'admin' then raise exception 'campusdesk:already_admin' using errcode = 'P0001'; end if;
  update public.profiles set role = 'admin', decided_by = auth.uid(), decided_at = now() where id = p_user;
  insert into public.audit_logs (actor_id, action, target_table, target_id, details) values (auth.uid(), 'admin_promoted', 'profiles', p_user, jsonb_build_object('previous_role', p.role));
  return jsonb_build_object('id', p_user, 'role', 'admin');
end $$;

revoke execute on function public.admin_account_counts(), public.admin_list_accounts(text, text, text, int, int), public.admin_get_account(uuid),
  public.admin_provision_account(uuid, text, jsonb, boolean), public.admin_reject_account(uuid, text), public.admin_suspend_account(uuid, text),
  public.admin_reactivate_account(uuid), public.admin_promote_to_admin(uuid) from public;
revoke execute on function public.my_account_state() from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    grant execute on function public.admin_account_counts(), public.admin_list_accounts(text, text, text, int, int), public.admin_get_account(uuid),
      public.admin_provision_account(uuid, text, jsonb, boolean), public.admin_reject_account(uuid, text), public.admin_suspend_account(uuid, text),
      public.admin_reactivate_account(uuid), public.admin_promote_to_admin(uuid), public.my_account_state() to authenticated;
  end if;
end $$;
