-- #####################################################################
-- FRESH V2 DATABASE ONLY - DO NOT RUN ON AN EXISTING CAMPUSDESK V1 DATABASE
-- GENERATED by scripts/build-fresh.py - edit supabase/migrations/* instead.
-- #####################################################################

-- ---- from migrations/002_v2_fee_integrity.sql ----
create or replace function public.fee_payments_guard()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_fee numeric; v_confirmed numeric; v_remaining numeric;
begin
  if new.fee_structure_id is null then
    if tg_op = 'INSERT' and new.status <> 'due' then raise exception 'campusdesk:fee_required' using errcode = 'P0001'; end if;
    return new;
  end if;
  -- serialise all writes for the same student+fee: this is what makes concurrent requests safe
  perform pg_advisory_xact_lock(hashtextextended(new.student_id::text || ':' || new.fee_structure_id::text, 0));

  if tg_op = 'UPDATE' then
    if new.student_id is distinct from old.student_id or new.fee_structure_id is distinct from old.fee_structure_id then
      raise exception 'campusdesk:immutable' using errcode = 'P0001';
    end if;
    -- decided payments are final (blocks double verification and silent edits)
    if old.status in ('paid','partial','rejected')
       and (new.status is distinct from old.status or new.amount_paid is distinct from old.amount_paid) then
      raise exception 'campusdesk:already_decided' using errcode = 'P0001';
    end if;
    if old.status = 'pending_verification' and new.amount_paid is distinct from old.amount_paid then
      raise exception 'campusdesk:immutable' using errcode = 'P0001';
    end if;
  end if;

  if new.status <> 'due' and (new.amount_paid is null or new.amount_paid <= 0) then
    raise exception 'campusdesk:invalid_amount' using errcode = 'P0001';
  end if;

  if new.status in ('paid','partial','pending_verification')
     and (tg_op = 'INSERT' or old.status is distinct from new.status) then
    select amount into v_fee from public.fee_structure where id = new.fee_structure_id;
    select coalesce(sum(amount_paid), 0) into v_confirmed from public.fee_payments
     where student_id = new.student_id and fee_structure_id = new.fee_structure_id
       and status in ('paid','partial') and id is distinct from new.id;
    v_remaining := v_fee - v_confirmed;
    if v_remaining <= 0 then raise exception 'campusdesk:already_paid' using errcode = 'P0001'; end if;
    if new.amount_paid > v_remaining then
      raise exception 'campusdesk:exceeds_remaining' using errcode = 'P0001', detail = v_remaining::text;
    end if;
    if new.status = 'pending_verification' and exists (
         select 1 from public.fee_payments where student_id = new.student_id
            and fee_structure_id = new.fee_structure_id and status = 'pending_verification' and id is distinct from new.id) then
      raise exception 'campusdesk:pending_exists' using errcode = 'P0001';
    end if;
    if new.status in ('paid','partial') then
      new.status := case when v_confirmed + new.amount_paid >= v_fee then 'paid' else 'partial' end;
    end if;
  end if;
  return new;
end $$;

drop trigger if exists fee_payments_guard on public.fee_payments;
create trigger fee_payments_guard before insert or update on public.fee_payments
  for each row execute procedure public.fee_payments_guard();

-- ---- from migrations/003_v2_report_support.sql ----
drop trigger if exists students_assign_code on public.students;
create trigger students_assign_code before insert on public.students
  for each row execute procedure public.assign_student_code();
drop trigger if exists teachers_assign_code on public.teachers;
create trigger teachers_assign_code before insert on public.teachers
  for each row execute procedure public.assign_teacher_code();

-- ---- from migrations/005_v2_notifications.sql ----
drop trigger if exists notices_notify on public.notices;
create trigger notices_notify after insert on public.notices for each row execute procedure public.trg_notice_notify();
drop trigger if exists results_notify on public.results;
create trigger results_notify after insert or update of published on public.results for each row execute procedure public.trg_result_notify();
drop trigger if exists fee_payments_notify on public.fee_payments;
create trigger fee_payments_notify after insert or update of status on public.fee_payments for each row execute procedure public.trg_fee_notify();
drop trigger if exists leave_notify on public.leave_requests;
create trigger leave_notify after insert or update of status on public.leave_requests for each row execute procedure public.trg_leave_notify();
drop trigger if exists timetable_notify on public.timetable;
create trigger timetable_notify after insert or update or delete on public.timetable for each row execute procedure public.trg_timetable_notify();
drop trigger if exists events_notify on public.events;
create trigger events_notify after insert on public.events for each row execute procedure public.trg_event_notify();
drop trigger if exists queries_notify on public.teacher_queries;
create trigger queries_notify after insert or update of status on public.teacher_queries for each row execute procedure public.trg_query_notify();
drop trigger if exists attendance_notify on public.attendance;
create trigger attendance_notify after insert or update of status on public.attendance for each row execute procedure public.trg_attendance_notify();

-- ---- from migrations/006_v2_leave_attendance_timetable.sql ----
drop trigger if exists leave_requests_guard on public.leave_requests;
create trigger leave_requests_guard before insert or update on public.leave_requests
  for each row execute procedure public.leave_requests_guard();
drop trigger if exists timetable_conflict_guard on public.timetable;
create trigger timetable_conflict_guard before insert or update on public.timetable
  for each row execute procedure public.timetable_conflict_guard();

-- ---- from migrations/900_OPTIONAL_security_hardening.sql ----
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
drop trigger if exists guard_profile_update on public.profiles;
create trigger guard_profile_update before update on public.profiles for each row execute procedure public.guard_profile_update();
